title: ebraminio.github.io
description: گیت‌هاب نوشته‌ها
lang: fa
theme: jekyll-theme-cayman
markdown: kramdown
show_downloads: false
google_analytics:

author:
  name: Ebrahim Byagowi
  name_fa: ابراهیم بیاگوی
  email: ebrahim@gnu.org
  github: ebraminio
  twitter: ebraminio

plugins:
  - jekyll-mentions
  - jekyll-feed
