title: ebraminio.github.io
description: 'Welcome'
lang: fa
theme: jekyll-theme-cayman
markdown: kramdown
show_downloads: false
google_analytics:

author:
  name: Ebrahim
  name_fa: Ebrahim
  email: ebrahim@gnu.org
  github: ebraminio

plugins:
  - jekyll-mentions
  - jekyll-feed
